[profile.default]
solc_version = '0.8.15'
fs_permissions = [{ access = "read", path = "./deployments.json"}]


[rpc_endpoints]
# Mainnets
ethereum = "${ETHEREUM_URL}"
polygon = "${POLYGON_URL}"
arbitrum = "${ARBITRUM_URL}"
optimism = "${OPTIMISM_URL}"
base = "${BASE_URL}"
cronos = "${CRONOS_URL}"
mantle = "${MANTLE_URL}"

# Testnets
sepolia = "${SEPOLIA_URL}"
goerli = "${GOERLI_URL}"
mumbai = "${MUMBAI_URL}"
local = "${LOCAL_URL}"
