[profile.default]
solc_version = '0.8.15'

remappings = [
    "@safe/=lib/safe-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",

    "@pwn-safe/=src/",
    "@pwn-safe-test/=test/"
]
