name: Test CI

on: push

jobs:
  build:
    name: Unit tests

    env:
      ETHEREUM_URL: ${{ secrets.ETHEREUM_URL }}
      POLYGON_URL: ${{ secrets.POLYGON_URL }}
      GOERLI_URL: ${{ secrets.GOERLI_URL }}
      MUMBAI_URL: ${{ secrets.MUMBAI_URL }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Run unit tests
        run: forge test --match-path "test/unit/*"

      - name: Run integration tests
        run: forge test --match-path "test/integration/*"
